server:
  port: 8001
spring:
  application:
    name: springboot_rabbit_sender
  rabbitmq:
    host: 94.191.58.120
    port: 5672
    username: admin1
    password: admin
    publisher-confirms: true #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)